# SPDX-License-Identifier: GPL-2.0

load("//vendor/amlogic/kernel:kernel_platform.bzl", "amlogic_kernel_platform")
load("//vendor/amlogic/gpu-modules/bifrost:defs.bzl", "mali_bifrost_module")
load("//vendor/amlogic/media-modules:defs.bzl", "media_modules_module")
load("//vendor/amlogic/common_drivers:defs.bzl", "common_drivers_module")
load(":modules.bzl", "COMMON_DRIVERS_MODULES", "KVIM3L_MODULES")

package(
    default_visibility = ["//visibility:public"],
)

mali_bifrost_module(name = "gpu_bifrost", kernel_build = ":kvim3l", deps = [":common_drivers"])

media_modules_module(name = "media", kernel_build = ":kvim3l", deps = [":common_drivers"])

common_drivers_module(name = "common_drivers", kernel_build = ":kvim3l", outs = COMMON_DRIVERS_MODULES)

amlogic_kernel_platform(
    name = "kvim3l",
    dtb_outs = [
        "kvim3l.dtb",
        "android_overlay_dt.dtbo",
    ],
    module_outs = KVIM3L_MODULES,
    build_config = "//vendor/amlogic/kernel:build.config.kvim3l.bazel",
    kmi_symbol_list = "//vendor/amlogic/kernel:android/abi_gki_aarch64_amlogic",
    kernel_modules = [
        ":gpu_bifrost",
        ":media",
        ":common_drivers",
    ],
)
